server:
  port: 8888

application:
  name: Simple Spring Boots Application


config:
    datasource:
        driverClass     : com.mysql.jdbc.Driver
        jdbcUrl         : jdbc:mysql://localhost/zengcode
        user            : root
        password        : pingu123
        maxIdleTime     : 3600
        checkoutTimeout : 2000

spring:
    application:
        name: zengcode
    freemarker:
        cache: false # This should be set to true in production.
    mvc:
        locale: No_no
        date-format: yyyy-MM-dd'T'HH:mm:ss.SSSZ
    jackson:
        date-format: yyyy-MM-dd'T'HH:mm:ss.SSSZ # Controls the date format in the REST api and where Jackson is used by Spring.

liquibase:
    change-log: classpath:/liquibase/application.db.changelog.xml
    drop-first: false
    enabled: true